### ISSUE TITLE
Alternative architecture / OS syscall support

### ISSUE THREAD

**Issue by elimirks** [elimirks/BlarbVM#8]
Right now the standard library (and the VM code itself) use 64 bit syscall codes exclusively.

**Comment by frolv** [comment]
You can use the `SYS_*` constants provided by `syscall.h`.

**Comment by elimirks** [comment]
I've been thinking about this recently... right now, most of the syscalls will directly call the `syscall` function inside the VM. Thus, Blarb code will have to call different syscalls depending on which OS it's being run on. I think it's time to create an abstraction layer of "Blarb Syscalls". For simplicity, I'll probably end up basing it largely off the 64 bit Linux syscalls numbers. That should make a BSD / MacOS port much easier... and maybe... just maybe... in the far future, a Windows port will arise.
